#!/usr/bin/env bash

#######################################################################
# NATS NKey Generation Script for TaleTrail Content Generator
#
# This script generates NKey pairs for all services in the system:
# - story-generator
# - quality-control
# - constraint-enforcer
# - prompt-helper
# - orchestrator
# - gateway
# - nats-cli
#
# For each service, it creates:
# - <service>.nk: Private key (NEVER commit to git)
# - <service>.pub: Public key (used in authorization)
#
# It also generates users.conf with complete authorization configuration
# that can be included in nats-server.conf
#
# Usage:
#   ./generate-nkeys.sh
#
# Requirements:
#   - nats command (NATS CLI)
#   - Install: https://github.com/nats-io/natscli
#######################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Service names that need NKeys
SERVICES=(
  "story-generator"
  "quality-control"
  "constraint-enforcer"
  "prompt-helper"
  "orchestrator"
  "gateway"
  "nats-cli"
)

# Check if nats command is available
if ! command -v nats &> /dev/null; then
    echo -e "${RED}ERROR: 'nats' command not found${NC}"
    echo ""
    echo "The NATS CLI is required to generate NKeys."
    echo "Install it using one of these methods:"
    echo ""
    echo "  macOS (Homebrew):"
    echo "    brew install nats-io/nats-tools/nats"
    echo ""
    echo "  Go install:"
    echo "    go install github.com/nats-io/natscli/nats@latest"
    echo ""
    echo "  Linux (download binary):"
    echo "    # Visit https://github.com/nats-io/natscli/releases"
    echo "    # Download the appropriate binary for your platform"
    echo ""
    echo "For more information, visit:"
    echo "  https://github.com/nats-io/natscli"
    exit 1
fi

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  NATS NKey Generation for TaleTrail${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Backup existing files if they exist
if ls *.nk >/dev/null 2>&1 || ls *.pub >/dev/null 2>&1 || [ -f "users.conf" ]; then
    BACKUP_DIR="backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    echo -e "${YELLOW}Backing up existing keys to: $BACKUP_DIR${NC}"
    mv *.nk "$BACKUP_DIR/" 2>/dev/null || true
    mv *.pub "$BACKUP_DIR/" 2>/dev/null || true
    mv users.conf "$BACKUP_DIR/" 2>/dev/null || true
    echo ""
fi

# Generate NKeys for each service
echo -e "${GREEN}Generating NKeys for services...${NC}"
echo ""

for service in "${SERVICES[@]}"; do
    echo -e "  ${BLUE}Generating:${NC} $service"

    # Generate NKey and capture output
    NKEY_OUTPUT=$(nats auth nkey gen user --public 2>&1)

    # Extract private and public keys
    PRIVATE_KEY=$(echo "$NKEY_OUTPUT" | grep -E '^SU' | head -1)
    PUBLIC_KEY=$(echo "$NKEY_OUTPUT" | grep -E '^U[A-Z]' | grep -v '^SU' | head -1)

    if [ -z "$PRIVATE_KEY" ] || [ -z "$PUBLIC_KEY" ]; then
        echo -e "${RED}ERROR: Failed to generate NKey for $service${NC}"
        exit 1
    fi

    # Save keys to files
    echo "$PRIVATE_KEY" > "${service}.nk"
    echo "$PUBLIC_KEY" > "${service}.pub"

    # Set proper permissions (private key should be read-only for owner)
    chmod 600 "${service}.nk"
    chmod 644 "${service}.pub"

    echo -e "    ${GREEN}✓${NC} Private key: ${service}.nk (600)"
    echo -e "    ${GREEN}✓${NC} Public key:  ${service}.pub (644)"
done

echo ""
echo -e "${GREEN}Generating users.conf...${NC}"

# Generate users.conf with complete authorization configuration
cat > users.conf << EOF
# NATS User Authorization Configuration
#
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# This file is automatically generated by generate-nkeys.sh
# DO NOT edit manually - regenerate using the script instead
#
# NKey Authentication with Subject-Level Permissions
# Each service has least-privilege access to only required subjects

users: [
  # Test Client - broad permissions for integration testing
  {
    user: "test"
    password: "test"
    permissions: {
      publish: {
        allow: [">"]
      }
      subscribe: {
        allow: [">"]
      }
    }
  },

  # Story Generator - can publish stories and events, subscribe to requests
  {
    nkey: "$(cat story-generator.pub)"
    permissions: {
      publish: {
        allow: ["mcp.story.response.>", "mcp.events.story.>"]
      }
      subscribe: {
        allow: ["mcp.story.generate", "mcp.orchestrator.story.>"]
      }
    }
  },

  # Quality Control - can publish validation results and events
  {
    nkey: "$(cat quality-control.pub)"
    permissions: {
      publish: {
        allow: ["mcp.quality.response.>", "mcp.events.quality.>"]
      }
      subscribe: {
        allow: ["mcp.quality.validate", "mcp.orchestrator.quality.>"]
      }
    }
  },

  # Constraint Enforcer - can publish constraint results and events
  {
    nkey: "$(cat constraint-enforcer.pub)"
    permissions: {
      publish: {
        allow: ["mcp.constraint.response.>", "mcp.events.constraint.>"]
      }
      subscribe: {
        allow: ["mcp.constraint.enforce", "mcp.orchestrator.constraint.>"]
      }
    }
  },

  # Prompt Helper - can publish prompt optimization results and events
  {
    nkey: "$(cat prompt-helper.pub)"
    permissions: {
      publish: {
        allow: ["mcp.prompt.response.>", "mcp.events.prompt.>"]
      }
      subscribe: {
        allow: ["mcp.prompt.helper", "mcp.orchestrator.prompt.>"]
      }
    }
  },

  # Orchestrator - full coordination access
  {
    nkey: "$(cat orchestrator.pub)"
    permissions: {
      publish: {
        allow: ["mcp.orchestrator.>", "mcp.story.>", "mcp.quality.>", "mcp.constraint.>", "mcp.prompt.>"]
      }
      subscribe: {
        allow: ["mcp.events.>", "mcp.*.response.>"]
      }
    }
  },

  # Gateway - can send orchestrator requests, subscribe to events
  {
    nkey: "$(cat gateway.pub)"
    permissions: {
      publish: {
        allow: ["mcp.orchestrator.request", "mcp.gateway.>"]
      }
      subscribe: {
        allow: ["mcp.events.>", "mcp.orchestrator.response.>"]
      }
    }
  },

  # NATS CLI - testing and debugging tool with broad permissions
  {
    nkey: "$(cat nats-cli.pub)"
    permissions: {
      publish: {
        allow: [">"]
      }
      subscribe: {
        allow: [">"]
      }
    }
  }
]
EOF

echo -e "  ${GREEN}✓${NC} users.conf created with authorization rules"
echo ""

# Print summary
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Generation Complete${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}Generated files:${NC}"
for service in "${SERVICES[@]}"; do
    echo "  - ${service}.nk (private key - NEVER commit)"
    echo "  - ${service}.pub (public key)"
done
echo "  - users.conf (authorization configuration)"
echo ""

echo -e "${YELLOW}IMPORTANT SECURITY NOTES:${NC}"
echo "  1. Private keys (.nk files) contain sensitive credentials"
echo "  2. NEVER commit .nk files to version control"
echo "  3. Keep private keys secure and backed up separately"
echo "  4. The .gitignore is configured to prevent accidental commits"
echo ""

echo -e "${GREEN}Next steps:${NC}"
echo "  1. Ensure nats-server.conf includes: include \"nkeys/users.conf\""
echo "  2. Distribute private keys (.nk) to respective services securely"
echo "  3. Restart NATS server to apply new configuration"
echo ""

echo -e "${GREEN}Public keys for reference:${NC}"
for service in "${SERVICES[@]}"; do
    echo "  ${service}: $(cat ${service}.pub)"
done
echo ""

echo -e "${GREEN}✓ All done!${NC}"
